#!/usr/bin/env node
/**
 * Shared conformance suite for the JS implementation: run the engine over every
 * case in conformance/cases.json and assert it reproduces the committed golden
 * outputs in conformance/expected/ (generated by the Rust reference - see
 * conformance/README.md).
 *
 * Standalone: needs only Node and python3 (to read the canonical TOML sources,
 * the same way the demo build does) - the Rust toolchain is not required.
 *
 *   node test/conformance.mjs      (or: npm test)
 */
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { createRequire } from 'node:module';

const here = dirname(fileURLToPath(import.meta.url));
const repo = join(here, '..', '..');
const require = createRequire(import.meta.url);
const gb = require('../greenbook.js');

// Read a canonical TOML source via Python's stdlib tomllib (dates -> strings),
// matching docs/demo/build-data.mjs. Keeps the JS side free of npm dependencies.
function toml(relPath) {
  const py = 'import tomllib,json,sys; print(json.dumps(tomllib.load(open(sys.argv[1],"rb")), default=str))';
  return JSON.parse(execFileSync('python3', ['-c', py, join(repo, relPath)], { encoding: 'utf8' }));
}

// Canonicalise for an order-independent deep comparison across languages.
function canon(v) {
  if (Array.isArray(v)) return v.map(canon);
  if (v && typeof v === 'object') {
    return Object.keys(v).sort().reduce((o, k) => { o[k] = canon(v[k]); return o; }, {});
  }
  return v;
}
const eq = (a, b) => JSON.stringify(canon(a)) === JSON.stringify(canon(b));

const cases = JSON.parse(readFileSync(join(repo, 'conformance/cases.json'), 'utf8'));
let failures = 0;
for (const c of cases) {
  const schedule = toml(c.schedule);
  const products = toml(c.products);
  const record = gb.parseFhirBundle(readFileSync(join(repo, 'conformance/fixtures', c.fixture), 'utf8'));
  const result = gb.evaluate(record, schedule, products, c.evaluated_at);
  delete result.by_antigen; // JS-only coverage view; not part of the goldens

  const golden = JSON.parse(readFileSync(join(repo, 'conformance/expected', `${c.id}.json`), 'utf8'));
  if (eq(result, golden)) {
    console.log(`  ok   ${c.id}`);
  } else {
    failures++;
    console.log(`  FAIL ${c.id}`);
  }
}

console.log(failures === 0 ? '\nAll cases match the golden outputs.' : `\n${failures} case(s) diverged.`);
process.exit(failures === 0 ? 0 : 1);
